config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/invites/:event_id/new', to: 'invites#new'
  post '/invites', to: 'invites#create'

  resources :events, only: [:new, :index, :create, :show]
  resources :users, only: [:show, :new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :description, presence: true
  validates :creator_id, presence: true
  validates :date, presence: true
  belongs_to :creator, class_name: 'User'
  has_many :invites, foreign_key: 'attended_event_id'
  has_many :attendees, through: :invites
  scope :upcoming, -> { where('date > ?', DateTime.now) }
  scope :past, -> { where('date <= ?', DateTime.now) }
end

app/models/invite.rb
class Invite < ApplicationRecord
  validates :attended_event_id, presence: true
  validates :attendee_id, presence: true, uniqueness: { scope: :attended_event_id }

  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  has_many :events, foreign_key: 'creator_id'
  has_many :invites, foreign_key: 'attendee_id'
  has_many :attending_events, through: :invites, source: :attended_event

  def upcoming_events
    attending_events.where('date > ?', DateTime.now)
  end

  def previous_events
    attending_events.where('date <= ?', DateTime.now)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ApplicationHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
    redirect_to login_path unless logged_in?
  end

  def index
    @upcoming_events = Event.upcoming
    @past_events = Event.past
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def show
    @event = Event.find_by(id: params[:id])
  end

  private

  def event_params
    params.require(:event).permit(:description, :date)
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  def new
    @invite = Invite.new
    @event = Event.find_by(id: params[:event_id])
    redirect_to @event unless @event.creator == current_user
  end

  def create
    invited_user = User.find_by(id: params[:invite][:attendee_id])
    event = Event.find_by(id: params[:invite][:event_id])
    if invited_user && event
      invite = event.invites.build(attendee_id: invited_user.id)
      if invite.save
        redirect_to event
      else
        @invite = Invite.new
        @event = Event.find_by(params[:invite][:event_id])
        render 'new'
      end
    else
      @invite = Invite.new
      @event = Event.find_by(params[:invite][:event_id])
      render 'new'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(name: params[:session][:name])
    if user
      session[:user_id] = user.id
      redirect_to user
    else
      render 'new'
    end
  end

  def destroy
    session.destroy
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    redirect_to current_user if logged_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    @events = @user.events
    @attending_events = @user.attending_events
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
Upcoming Events <br>
<% @upcoming_events.each do |e|%>
  <%= e.creator.name%> <br> 
  <%= e.description%> <br> 
  <%= e.date%> <br>
<% end%>

Past Events <br>
<% @past_events.each do |e|%>
  <%= e.creator.name%> <br> 
  <%= e.description%> <br> 
  <%= e.date%> <br>
<% end%>

app/views/events/new.html.erb
<%= form_for @event do |f|%>
<%= f.label :description %>
<%= f.text_area :description %>
<%= f.label :date %>
<%= f.date_field :date %>
<%= f.submit "Create Event" %>
<% end %>

app/views/events/show.html.erb
<%= @event.creator.name%>, <%= @event.description%>

<br>
Attendees: <br>
<% @event.attendees.each do |attendee| %>
  <%= attendee.name %> <br>
<% end %>
<%= link_to "Invite", invites_url + "/" + @event.id.to_s + "/new" %>

app/views/invites/new.html.erb
<%= form_for @invite do |f| %>
  <%= f.label :attendee_id %>
  <%= f.text_field :attendee_id %>
  <%= f.hidden_field :event_id, value: @event.id %>
  <%= f.submit "Invite" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if !current_user.nil? %>
      <%= link_to current_user.name, current_user %>
      <%= link_to "Create new event", new_event_path %>
      <%= link_to "Events", events_path %>
      <%= link_to "Logout", logout_path, method: :delete %>
      <br>
    <% else %>
      <%= link_to "Login", login_path %>
      <%= link_to "Signup", new_user_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit "Create" %>
<% end %>

app/views/users/show.html.erb
<%= @user.name %> 
<br>

Created events: <br>
<% @events.each do |e| %>
  <%= link_to e.id, e %> <br>
  <%= e.description %> <br>
  <%= e.date %> <br>
<% end %>

<br>

Upcoming events: <br>
<% @user.upcoming_events.each do |e| %>
  <%= e.description%> <br> 
  <%= e.date%> <br>
<% end %>

Previous events: <br>
<% @user.previous_events.each do |e| %>
  <%= e.description%> <br> 
  <%= e.date%> <br>
<% end %>